neofetch
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '


#Personalizacion

#Wal
export PATH="${PATH}:${HOME}/.local/bin/"

#kitty
cat ~/.cache/wal/sequences

alias ll='ls'
