--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/juan/Pictures/Wallpapers/smoke4k1.jpg"

-- Special
background="#0c0c0a"
foreground="#b2bab7"
cursor="#b2bab7"

-- Colors
color0="#0c0c0a"
color1="#5E675A"
color2="#9E1210"
color3="#F11706"
color4="#FE6004"
color5="#FE9E06"
color6="#DAC22C"
color7="#b2bab7"
color8="#7c8280"
color9="#5E675A"
color10="#9E1210"
color11="#F11706"
color12="#FE6004"
color13="#FE9E06"
color14="#DAC22C"
color15="#b2bab7"
