--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/juan/Pictures/Wallpapers/simpson.jpg"

-- Special
background="#11100d"
foreground="#cadeec"
cursor="#cadeec"

-- Colors
color0="#11100d"
color1="#7B8670"
color2="#FED421"
color3="#AFA558"
color4="#3173A9"
color5="#67A7C9"
color6="#909DA1"
color7="#cadeec"
color8="#8d9ba5"
color9="#7B8670"
color10="#FED421"
color11="#AFA558"
color12="#3173A9"
color13="#67A7C9"
color14="#909DA1"
color15="#cadeec"
