# Shell variables
# Generated by 'wal'
wallpaper='/home/juan/Pictures/Wallpapers/smoke4k1.jpg'

# Special
background='#0c0c0a'
foreground='#b2bab7'
cursor='#b2bab7'

# Colors
color0='#0c0c0a'
color1='#5E675A'
color2='#9E1210'
color3='#F11706'
color4='#FE6004'
color5='#FE9E06'
color6='#DAC22C'
color7='#b2bab7'
color8='#7c8280'
color9='#5E675A'
color10='#9E1210'
color11='#F11706'
color12='#FE6004'
color13='#FE9E06'
color14='#DAC22C'
color15='#b2bab7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
